default_platform(:android)

platform :android do
  desc  "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:1093915227391:android:5af2cdacc73d8fe4ebc8ca",
        firebase_cli_token: "1//0359Ib33JH_lSCgYIARAAGAMSNwF-L9IrmzOrz6Il84OYw-Zp5cb33Ta4XQ1rj-TNzlcZAtQC1XOKtVgubIOKM0EUjDqTs3mSuUE",
        # android_artifact_type : "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "mostfammaaggddyy@gmail.com",
        release_notes: "First Fastlane Firebase Distribution Radary App"
  )
  end
end
