default_platform(:android)

platform :android do
  desc  "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:1093915227391:android:5af2cdacc73d8fe4ebc8ca",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"] ,
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "mostfammaaggddyy@gmail.com,aymansalleh333@gmail.com,ayahemdan2468@gmail.com,zeyadosama15@gmail.com",
        release_notes: "Add verstion 1.2.7",
  )
  end
end
